CREATE DATABASE SITELOG;
USE SITELOG;

CREATE TABLE '사이트이름' (
	id VARCHAR(400) NOT NULL,
    title VARCHAR(150) NOT NULL,
    url VARCHAR(500),
    datetime DATETIME NOT NULL,
    PRIMARY KEY (id)
);

CREATE DATABASE SUBSCRIPTION;
USE SUBSCRIPTION;

CREATE TABLE USER (
	id VARCHAR(6) NOT NULL,
    chatid BIGINT NOT NULL,
    name VARCHAR(5) NOT NULL,
    plan VARCHAR(5) NOT NULL,
    date_enrolled DATETIME NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE WEBSITE (
    id TINYINT UNSIGNED NOT NULL AUTO_INCREMENT,
    site_name VARCHAR(30) NOT NULL,
    url VARCHAR(150) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE SUBSCRIPTION (
    id SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
    website_id TINYINT UNSIGNED NOT NULL,
    date_start DATETIME NOT NULL,
    user_id VARCHAR(6) NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT subscription_references_website FOREIGN KEY (website_id) REFERENCES WEBSITE (id),
    CONSTRAINT subscription_references_user FOREIGN KEY (user_id) REFERENCES USER (id)
);

CREATE TABLE NOTICE_LOG (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT,
    subscription_id SMALLINT UNSIGNED NOT NULL,
    message_info VARCHAR(1000) NOT NULL,
    datetime DATETIME NOT NULL,
    PRIMARY KEY (id)
);